---
  - name: Install dependencies
    become: True
    apt:
      state: present
      update_cache: yes
      cache_valid_time: 1800
      name:
        - dnsutils

  - name: Create installation directory
    become: True
    file:
      path: /opt/le-dns
      state: directory
      owner: root
      group: root
      mode: 0750

  - name: Create delegation script
    become: True
    when: ledns_provide_remote
    template:
      src: upddns.sh.j2
      dest: /opt/le-dns/upddns.sh
      owner: root
      group: root
      mode: 0750

  - name: Install dehydrated
    become: True
    get_url:
      url: https://github.com/lukas2511/dehydrated/raw/05eda91a2fbaed1e13c733230238fc68475c535e/dehydrated
      dest: /opt/le-dns/dehydrated
      owner: root
      group: root
      mode: 0755
      sha256sum: a97b0d64d5ecc21549a58b714bb9017479b38b2e40ff51c04f1638e71291d138

  - name: Upload hook and configuration
    become: True
    template:
      src: "{{ item.name }}.j2"
      dest: "/opt/le-dns/{{ item.name }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
    with_items:
      - name: dnshook.sh
        mode: '0750'
      - name: domains.txt
        mode: '0640'
      - name: config
        mode: '0640'

  - name: Upload le-dns service and timer
    become: True
    template:
      src: "{{ item }}.j2"
      dest: "/etc/systemd/system/{{ item }}"
      owner: root
      group: root
      mode: 0644
    notify: reload
    with_items:
      - le-dns.service
      - le-dns.timer
